# Lab | Pandas Deep-Dive

### 1. Import Pandas package under the alias pd and Numpy under the alias np

In [134]:
import pandas as pd
import numpy as np

### 2. Define a variable called `path` that contains the path to the csv file you downloaded. 

In [135]:
path = r"C:\Users\ccior\IRONHACK\2.2-lab_pandas_deepdive\your-code\data\apple_store.csv"

In [136]:
#path = "C:\Users\ccior\IRONHACK\2.2-lab_pandas_deepdive\your-code\data\apple_store.csv" ASÍ PUEDE HABER PROBLEMAS CON \n

# path = r"C:\Users\ccior\IRONHACK\2.2-lab_pandas_deepdive\your-code\data\apple_store.csv" NO HAY PROBLEMAS

# path "apple_store.csv" y "./apple_store.csv" si el archivo a abrir está en el directorio de trabajo en el que estoy

# "../apple_store.csv" el archivo está en la carpeta inmediatamente anterior

### 3. Using the Pandas `read_csv()` method, import the csv file at the path above. 

Assign the returned value to a variable called `data`.

Note: you can omit the `sep` parameter for `read_csv()` because the csv file uses the default separator of ",".

In [137]:
data = pd.read_csv(path)

### 4. Print the first 5 rows of `data` to see what the data look like.

A data analyst usually does this to have a general understanding about what the data look like before digging deep.

In [138]:
raw_data = data.copy()

In [139]:
data.head()

id                                         track_name  size_bytes  \
0  281656475                                    PAC-MAN Premium   100788224   
1  281796108                          Evernote - stay organized   158578688   
2  281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   100524032   
3  282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   128512000   
4  282935706                                              Bible    92774400   

   price  rating_count_tot  rating_count_ver  user_rating  user_rating_ver  \
0   3.99             21292                26          4.0              4.5   
1   0.00            161065                26          4.0              3.5   
2   0.00            188583              2822          3.5              4.5   
3   0.00            262241               649          4.0              4.5   
4   0.00            985920              5320          4.5              5.0   

    prime_genre  
0         Games  
1  Productivity  
2       Weather  
3      Shopping  
4     Reference

### 5. Print the summary (info) of the data.

In [140]:
summary = data.describe()
summary.head()

id    size_bytes        price  rating_count_tot  \
count  7.197000e+03  7.197000e+03  7197.000000       7197.000000   
mean   8.631310e+08  1.991345e+08     1.726218      12892.907184   
std    2.712368e+08  3.592069e+08     5.833006      75739.408675   
min    2.816565e+08  5.898240e+05     0.000000          0.000000   
25%    6.000937e+08  4.692275e+07     0.000000         28.000000   

       rating_count_ver  user_rating  user_rating_ver  
count       7197.000000  7197.000000      7197.000000  
mean         460.373906     3.526956         3.253578  
std         3920.455183     1.517948         1.809363  
min            0.000000     0.000000         0.000000  
25%            1.000000     3.500000         2.500000

In [141]:
summary.transpose()

count          mean           std          min  \
id                7197.0  8.631310e+08  2.712368e+08  281656475.0   
size_bytes        7197.0  1.991345e+08  3.592069e+08     589824.0   
price             7197.0  1.726218e+00  5.833006e+00          0.0   
rating_count_tot  7197.0  1.289291e+04  7.573941e+04          0.0   
rating_count_ver  7197.0  4.603739e+02  3.920455e+03          0.0   
user_rating       7197.0  3.526956e+00  1.517948e+00          0.0   
user_rating_ver   7197.0  3.253578e+00  1.809363e+00          0.0   

                          25%          50%           75%           max  
id                600093661.0  978148241.0  1.082310e+09  1.188376e+09  
size_bytes         46922752.0   97153024.0  1.819249e+08  4.025970e+09  
price                     0.0          0.0  1.990000e+00  2.999900e+02  
rating_count_tot         28.0        300.0  2.793000e+03  2.974676e+06  
rating_count_ver          1.0         23.0  1.400000e+02  1.770500e+05  
user_rating               3.5          4.0  4.500000e+00  5.000000e+00  
user_rating_ver           2.5          4.0  4.500000e+00  5.000000e+00

### 6. Print the number of columns in the data.

In [142]:
len(data.columns)

9

### 7. Print all column names.

In [143]:
data.columns.values

array(['id', 'track_name', 'size_bytes', 'price', 'rating_count_tot',
       'rating_count_ver', 'user_rating', 'user_rating_ver',
       'prime_genre'], dtype=object)

## Now that we have a general understanding of the data, we'll start working on the challenge questions.

### 8. How many apps are there in the data source? 

Print the # of observations of the data.

*Hint: Your code should return the number 7197.*

In [144]:
data["track_name"].value_counts()

VR Roller Coaster                                   2
Mannequin Challenge                                 2
PAC-MAN Premium                                     1
European Qualifiers Official App                    1
Tooth Fairy Princess - Magical Adventure            1
                                                   ..
Heart of Vegas Slots – Casino Slot Machine Games    1
赤ペン 提出カメラ                                           1
J&J Official 7 Minute Workout                       1
Beautiful Japanese Handwriting                      1
Escape the Sweet Shop Series                        1
Name: track_name, Length: 7195, dtype: int64

In [145]:
data["track_name"] == "VR Roller Coaster" #para filtrar haciendo booleano

0       False
1       False
2       False
3       False
4       False
        ...  
7192    False
7193    False
7194    False
7195    False
7196    False
Name: track_name, Length: 7197, dtype: bool

In [146]:
data[data["track_name"] == "VR Roller Coaster"]

id         track_name  size_bytes  price  rating_count_tot  \
3319   952877179  VR Roller Coaster   169523200    0.0               107   
5603  1089824278  VR Roller Coaster   240964608    0.0                67   

      rating_count_ver  user_rating  user_rating_ver prime_genre  
3319               102          3.5              3.5       Games  
5603                44          3.5              4.0       Games

In [147]:
data["track_name"].value_counts().sum()

7197

In [148]:
data.shape[0]

7197

### 9. What is the average rating of all apps? 

First, read the `user_rating` column into a varialbe named `user_rating`.

In [149]:
user_rating = data['user_rating']
user_rating

0       4.0
1       4.0
2       3.5
3       4.0
4       4.5
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196    5.0
Name: user_rating, Length: 7197, dtype: float64

In [150]:
user_rating = data.user_rating
user_rating

0       4.0
1       4.0
2       3.5
3       4.0
4       4.5
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196    5.0
Name: user_rating, Length: 7197, dtype: float64

Now you can calculate the average of the `user_rating` data.

Your code should return 3.526955675976101

In [151]:
user_rating.mean()

3.526955675976101

### 10. How many apps have an average rating no less than 4?

First, filter `user_rating` where its value >= 4. 

Assign the filtered dataframe to a new variable called `user_rating_high`.

In [152]:
user_rating_high = user_rating[user_rating >= 4]

user_rating_high

0       4.0
1       4.0
3       4.0
4       4.5
5       4.0
       ... 
7192    4.5
7193    4.5
7194    4.5
7195    4.5
7196    5.0
Name: user_rating, Length: 4781, dtype: float64

In [153]:
user_rating_high = data[data["user_rating"] >= 4]
user_rating_high

id                                         track_name  \
0      281656475                                    PAC-MAN Premium   
1      281796108                          Evernote - stay organized   
3      282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   
4      282935706                                              Bible   
5      283619399                                   Shanghai Mahjong   
...          ...                                                ...   
7192  1187617475                                              Kubik   
7193  1187682390                                  VR Roller-Coaster   
7194  1187779532              Bret Michaels Emojis + Lyric Keyboard   
7195  1187838770          VR Roller Coaster World - Virtual Reality   
7196  1188375727                       Escape the Sweet Shop Series   

      size_bytes  price  rating_count_tot  rating_count_ver  user_rating  \
0      100788224   3.99             21292                26          4.0   
1      158578688   0.00            161065                26          4.0   
3      128512000   0.00            262241               649          4.0   
4       92774400   0.00            985920              5320          4.5   
5       10485713   0.99              8253              5516          4.0   
...          ...    ...               ...               ...          ...   
7192   126644224   0.00               142                75          4.5   
7193   120760320   0.00                30                30          4.5   
7194   111322112   1.99                15                 0          4.5   
7195    97235968   0.00                85                32          4.5   
7196    90898432   0.00                 3                 3          5.0   

      user_rating_ver   prime_genre  
0                 4.5         Games  
1                 3.5  Productivity  
3                 4.5      Shopping  
4                 5.0     Reference  
5                 4.0         Games  
...               ...           ...  
7192              4.5         Games  
7193              4.5         Games  
7194              0.0     Utilities  
7195              4.5         Games  
7196              5.0         Games  

[4781 rows x 9 columns]

In [154]:
user_rating_high = data.track_name[data["user_rating"] >= 4]
user_rating_high

0                                         PAC-MAN Premium
1                               Evernote - stay organized
3       eBay: Best App to Buy, Sell, Save! Online Shop...
4                                                   Bible
5                                        Shanghai Mahjong
                              ...                        
7192                                                Kubik
7193                                    VR Roller-Coaster
7194                Bret Michaels Emojis + Lyric Keyboard
7195            VR Roller Coaster World - Virtual Reality
7196                         Escape the Sweet Shop Series
Name: track_name, Length: 4781, dtype: object

Now obtain the length of `user_rating_high` which should return 4781.

In [155]:
user_rating_high = user_rating[user_rating >= 4]

In [156]:
len(user_rating_high)

4781

### 11. How many genres are there in total for all the apps?

Define a new variable named `genres` that contains the `prime_genre` column of `data`. Google for how to obtain unique values of a dataframe column. 

In [157]:
#así me da igual que haya espacios en los nombres de las columnas.

genres = data["prime_genre"].unique()
genres

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

In [158]:
#la otra manera, si no hay espacios en el nombre.

genres = data.prime_genre.unique()

genres

array(['Games', 'Productivity', 'Weather', 'Shopping', 'Reference',
       'Finance', 'Music', 'Utilities', 'Travel', 'Social Networking',
       'Sports', 'Business', 'Health & Fitness', 'Entertainment',
       'Photo & Video', 'Navigation', 'Education', 'Lifestyle',
       'Food & Drink', 'News', 'Book', 'Medical', 'Catalogs'],
      dtype=object)

Print the length of the unique values of `genres`. Your code should return 23.

In [159]:
len(genres)

23

### 12. What are the top 3 genres that have the most number of apps?

What you want to do is to count the number of occurrences of each unique genre values. Because you already know how to obtain the unique genre values, you can of course count the # of apps of each genre one by one. However, Pandas has a convient function to let you count all values of a dataframe column with a single command. Google for "pandas count values" to find the solution. Your code should return the following:

```
Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64
```

In [160]:
data.prime_genre.value_counts().head(3)

Games            3862
Entertainment     535
Education         453
Name: prime_genre, dtype: int64

In [161]:
data.prime_genre.value_counts()

Games                3862
Entertainment         535
Education             453
Photo & Video         349
Utilities             248
Health & Fitness      180
Productivity          178
Social Networking     167
Lifestyle             144
Music                 138
Shopping              122
Sports                114
Book                  112
Finance               104
Travel                 81
News                   75
Weather                72
Reference              64
Food & Drink           63
Business               57
Navigation             46
Medical                23
Catalogs               10
Name: prime_genre, dtype: int64

### 13. Which genre is most likely to contain free apps?

First, filter `data` where the price is 0.00. Assign the filtered data to a new variable called `free_apps`. Then count the values in `free_apps`. Your code should return:

```
Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Navigation             20
Reference              20
Business               20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64
```

In [162]:
free_apps = data[data.price == 0]
free_apps

id                                         track_name  \
1      281796108                          Evernote - stay organized   
2      281940292    WeatherBug - Local Weather, Radar, Maps, Alerts   
3      282614216  eBay: Best App to Buy, Sell, Save! Online Shop...   
4      282935706                                              Bible   
6      283646709             PayPal - Send and request money safely   
...          ...                                                ...   
7188  1186384912       Demolition Derby Virtual Reality (VR) Racing   
7192  1187617475                                              Kubik   
7193  1187682390                                  VR Roller-Coaster   
7195  1187838770          VR Roller Coaster World - Virtual Reality   
7196  1188375727                       Escape the Sweet Shop Series   

      size_bytes  price  rating_count_tot  rating_count_ver  user_rating  \
1      158578688    0.0            161065                26          4.0   
2      100524032    0.0            188583              2822          3.5   
3      128512000    0.0            262241               649          4.0   
4       92774400    0.0            985920              5320          4.5   
6      227795968    0.0            119487               879          4.0   
...          ...    ...               ...               ...          ...   
7188   168774656    0.0                18                18          4.0   
7192   126644224    0.0               142                75          4.5   
7193   120760320    0.0                30                30          4.5   
7195    97235968    0.0                85                32          4.5   
7196    90898432    0.0                 3                 3          5.0   

      user_rating_ver   prime_genre  
1                 3.5  Productivity  
2                 4.5       Weather  
3                 4.5      Shopping  
4                 5.0     Reference  
6                 4.5       Finance  
...               ...           ...  
7188              4.0         Games  
7192              4.5         Games  
7193              4.5         Games  
7195              4.5         Games  
7196              5.0         Games  

[4056 rows x 9 columns]

In [163]:
free_apps.prime_genre.value_counts()

Games                2257
Entertainment         334
Photo & Video         167
Social Networking     143
Education             132
Shopping              121
Utilities             109
Lifestyle              94
Finance                84
Sports                 79
Health & Fitness       76
Music                  67
Book                   66
Productivity           62
News                   58
Travel                 56
Food & Drink           43
Weather                31
Business               20
Reference              20
Navigation             20
Catalogs                9
Medical                 8
Name: prime_genre, dtype: int64

### 14. Now you can calculate the proportion of the free apps in each genre based on the value counts you obtained in the previous two steps. 

Challenge yourself by achieving that with one line of code. The output should look like:

```
Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64
```

The numbers are interesting, aren't they?

In [164]:
(free_apps.prime_genre.value_counts() / data.prime_genre.value_counts()).sort_values(ascending=False)

Shopping             0.991803
Catalogs             0.900000
Social Networking    0.856287
Finance              0.807692
News                 0.773333
Sports               0.692982
Travel               0.691358
Food & Drink         0.682540
Lifestyle            0.652778
Entertainment        0.624299
Book                 0.589286
Games                0.584412
Music                0.485507
Photo & Video        0.478510
Utilities            0.439516
Navigation           0.434783
Weather              0.430556
Health & Fitness     0.422222
Business             0.350877
Productivity         0.348315
Medical              0.347826
Reference            0.312500
Education            0.291391
Name: prime_genre, dtype: float64

### 15. If a developer tries to make money by developing and selling Apple Store apps, in which genre should s/he develop the apps? Please assume all apps cost the same amount of time and expense to develop.

We will leave this question to you. There are several way to solve it. Ideally your output should look like below:

```
    average_price              genre
21       8.776087            Medical
11       5.116316           Business
4        4.836875          Reference
6        4.835435              Music
1        4.330562       Productivity
15       4.124783         Navigation
16       4.028234          Education
12       1.916444   Health & Fitness
20       1.790536               Book
7        1.647621          Utilities
2        1.605417            Weather
18       1.552381       Food & Drink
14       1.473295      Photo & Video
0        1.432923              Games
8        1.120370             Travel
10       0.953070             Sports
13       0.889701      Entertainment
17       0.885417          Lifestyle
22       0.799000           Catalogs
19       0.517733               News
5        0.421154            Finance
9        0.339880  Social Networking
3        0.016311           Shopping
```

In [180]:
data_group = data.groupby('prime_genre').mean(numeric_only=True)
data_group

id    size_bytes     price  rating_count_tot  \
prime_genre                                                                 
Book               9.435737e+08  1.788206e+08  1.790536       5125.437500   
Business           6.934696e+08  6.416849e+07  5.116316       4788.087719   
Catalogs           9.521081e+08  5.018163e+07  0.799000       1732.500000   
Education          8.169410e+08  1.804242e+08  4.028234       2239.229581   
Entertainment      8.507593e+08  1.014787e+08  0.889701       7533.678505   
Finance            7.232960e+08  7.823586e+07  0.421154      11047.653846   
Food & Drink       7.313079e+08  7.759500e+07  1.552381      13938.619048   
Games              9.351898e+08  2.836583e+08  1.432923      13691.996634   
Health & Fitness   7.313714e+08  9.010664e+07  1.916444       9913.172222   
Lifestyle          8.270774e+08  6.230647e+07  0.885417       6161.763889   
Medical            7.458997e+08  3.763890e+08  8.776087        592.782609   
Music              7.566649e+08  1.096356e+08  4.835435      28842.021739   
Navigation         6.276328e+08  1.033545e+08  4.124783      11853.956522   
News               6.787318e+08  6.247085e+07  0.517733      13015.066667   
Photo & Video      7.965089e+08  6.852190e+07  1.473295      14352.280802   
Productivity       7.366445e+08  7.844064e+07  4.330562       8051.325843   
Reference          7.231377e+08  1.551627e+08  4.836875      22410.843750   
Shopping           6.593491e+08  9.334683e+07  0.016311      18615.327869   
Social Networking  7.912940e+08  7.937244e+07  0.339880      45498.898204   
Sports             7.403697e+08  7.887357e+07  0.953070      14026.929825   
Travel             6.285153e+08  8.270691e+07  1.120370      14129.444444   
Utilities          8.001238e+08  5.429006e+07  1.647621       6863.822581   
Weather            6.275585e+08  6.144138e+07  1.605417      22181.027778   

                   rating_count_ver  user_rating  user_rating_ver  
prime_genre                                                        
Book                      70.714286     2.477679         2.111607  
Business                 275.456140     3.745614         3.333333  
Catalogs                 344.600000     2.100000         2.100000  
Education                239.000000     3.376380         2.952539  
Entertainment            140.893458     3.246729         2.900000  
Finance                  250.576923     2.432692         1.634615  
Food & Drink             320.603175     3.182540         2.412698  
Games                    575.280166     3.685008         3.545184  
Health & Fitness         211.205556     3.700000         3.369444  
Lifestyle                712.111111     2.805556         2.218750  
Medical                   46.739130     3.369565         3.260870  
Music                    344.956522     3.978261         3.811594  
Navigation               110.195652     2.684783         2.152174  
News                     113.720000     2.980000         2.213333  
Photo & Video            282.830946     3.800860         3.485673  
Productivity             121.073034     4.005618         3.733146  
Reference                868.671875     3.453125         3.093750  
Shopping                 709.008197     3.540984         2.618852  
Social Networking        556.287425     2.985030         2.482036  
Sports                   128.447368     2.982456         2.548246  
Travel                   133.864198     3.376543         2.820988  
Utilities                755.036290     3.278226         2.862903  
Weather                  885.875000     3.597222         3.222222

In [183]:
data_group_byprice_unordered = data_group['price']
data_group_byprice_unordered

prime_genre
Book                 1.790536
Business             5.116316
Catalogs             0.799000
Education            4.028234
Entertainment        0.889701
Finance              0.421154
Food & Drink         1.552381
Games                1.432923
Health & Fitness     1.916444
Lifestyle            0.885417
Medical              8.776087
Music                4.835435
Navigation           4.124783
News                 0.517733
Photo & Video        1.473295
Productivity         4.330562
Reference            4.836875
Shopping             0.016311
Social Networking    0.339880
Sports               0.953070
Travel               1.120370
Utilities            1.647621
Weather              1.605417
Name: price, dtype: float64

In [184]:
data_group_byprice_unordered.sort_values(ascending=False)

prime_genre
Medical              8.776087
Business             5.116316
Reference            4.836875
Music                4.835435
Productivity         4.330562
Navigation           4.124783
Education            4.028234
Health & Fitness     1.916444
Book                 1.790536
Utilities            1.647621
Weather              1.605417
Food & Drink         1.552381
Photo & Video        1.473295
Games                1.432923
Travel               1.120370
Sports               0.953070
Entertainment        0.889701
Lifestyle            0.885417
Catalogs             0.799000
News                 0.517733
Finance              0.421154
Social Networking    0.339880
Shopping             0.016311
Name: price, dtype: float64